using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Municipality360.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddAIIntelligenceToReclamation : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "AIClassificationApplied",
                table: "Reclamations",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<float>(
                name: "AIConfidenceScore",
                table: "Reclamations",
                type: "real",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AIExtractedKeywords",
                table: "Reclamations",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "AIProcessedAt",
                table: "Reclamations",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<float>(
                name: "AISeverityScore",
                table: "Reclamations",
                type: "real",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AISuggestedCategory",
                table: "Reclamations",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AISuggestedPriorite",
                table: "Reclamations",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AutoGeneratedResponse",
                table: "Reclamations",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "AutoResponseSent",
                table: "Reclamations",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "AutoResponseSentAt",
                table: "Reclamations",
                type: "datetime2",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AIClassificationApplied",
                table: "Reclamations");

            migrationBuilder.DropColumn(
                name: "AIConfidenceScore",
                table: "Reclamations");

            migrationBuilder.DropColumn(
                name: "AIExtractedKeywords",
                table: "Reclamations");

            migrationBuilder.DropColumn(
                name: "AIProcessedAt",
                table: "Reclamations");

            migrationBuilder.DropColumn(
                name: "AISeverityScore",
                table: "Reclamations");

            migrationBuilder.DropColumn(
                name: "AISuggestedCategory",
                table: "Reclamations");

            migrationBuilder.DropColumn(
                name: "AISuggestedPriorite",
                table: "Reclamations");

            migrationBuilder.DropColumn(
                name: "AutoGeneratedResponse",
                table: "Reclamations");

            migrationBuilder.DropColumn(
                name: "AutoResponseSent",
                table: "Reclamations");

            migrationBuilder.DropColumn(
                name: "AutoResponseSentAt",
                table: "Reclamations");
        }
    }
}
